addSbtPlugin("com.dwijnand"       % "sbt-dynver"        % "4.0.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"      % "2.0.5")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"           % "0.3.7")
addSbtPlugin("ch.epfl.scala"      % "sbt-release-early" % "2.1.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"     % "1.6.0")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"          % "1.3.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"         % "1.3.2")
