addSbtPlugin("com.dwijnand"       % "sbt-dynver"        % "3.0.0")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"      % "1.6.0-RC3")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"           % "0.3.3")
addSbtPlugin("com.47deg"          % "sbt-microsites"    % "0.8.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-release-early" % "2.1.1")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"     % "1.5.1")
